# Generated by Django 4.2.11 on 2024-04-24 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rent', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
                ('amenities', models.CharField(max_length=255)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RentalInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_email', models.EmailField(max_length=254, unique=True)),
                ('insurance_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_email', models.EmailField(max_length=254, unique=True)),
                ('telephone_number', models.CharField(max_length=20)),
                ('provider_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.listing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.student')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityProvide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.property')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.utilityprovider')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='beyondCampus.university'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.property')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.student')),
            ],
        ),
        migrations.CreateModel(
            name='RequestMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(default='General', max_length=100)),
                ('description', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.property')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.student')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.listing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.student')),
            ],
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement_terms', models.TextField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.landlord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.student')),
            ],
        ),
        migrations.CreateModel(
            name='Occupy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.property')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.student')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordOwn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.property')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.listing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.student')),
            ],
        ),
        migrations.CreateModel(
            name='CoveredBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.rentalinsurance')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.property')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_num', models.IntegerField()),
                ('preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.listing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyondCampus.student')),
            ],
        ),
    ]
