# Generated by Django 4.2.11 on 2024-03-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyondCampus', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
