# Generated by Django 4.2.11 on 2024-03-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyondCampus', '0006_delete_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandlordOwns',
            new_name='LandlordOwn',
        ),
        migrations.RenameModel(
            old_name='Occupies',
            new_name='Occupy',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='UtilityProvides',
            new_name='UtilityProvide',
        ),
    ]
