# Generated by Django 4.2.11 on 2024-03-28 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyondCampus', '0007_rename_landlordowns_landlordown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='beyondCampus.university'),
            preserve_default=False,
        ),
    ]
